
print()
print("Keep Caps Lock On And Reply With Y or N")
print("If you input an invalid answer by default it will choose 'no'")
print("Answers are case sensitive")
print()

print("___________________________________")
print("| * Forest Pygame                  |")
print("|   Begin?                         |")
print("|__________________________________|")
print()
input("click here ane press enter to begin")
print()
input("Enter Name: ")
print()
print("___________________________________")
print("| * You find yourself in a forest. |")
print("|   You notice a river.            |")
print("|   Follow it?                     |")
print("|__________________________________|")
print()
des1 = input("(Y/N): ")
if des1 == "Y":
    print("___________________________________")
    print("| * You follow the river.          |")
    print("|   You are now hungry.            |")
    print("|   You see berries on a bush.     |")
    print("|   Eat Them?                      |")
    print("|__________________________________|")
    print()
    des2 = input("(Y/N): ")
    if des2 == "Y":
        print()
        print("YOU DIED OF FOOD POISONING")
    else:
        print("___________________________________")
        print("| * You keep moving.               |")
        print("|   You are still hungry.          |")
        print("|   You see distant lanterns.      |")
        print("|   approach Them?                 |")
        print("|__________________________________|")
        print()
        des4 = input("(Y/N): ")
        if des4 == "Y":
            print("___________________________________")
            print("| * You follow lanterns.           |")
            print("|   They are a group of hikers.    |")
            print("|   they bring you to their house. |")
            print("|   Enter?                         |")
            print("|__________________________________|")
            print()
            des5 = input("(Y/N): ")
            if des5 == "Y":
                print("___________________________________")
                print("| * The hikers feed you food.      |")
                print("|   They call a rescue helicopter. |")
                print("|   you reunite with your family.  |")
                print("|__________________________________|")
                print()
                print("___________________________________")
                print("| * You learn you had amnesia.     |")
                print("|   You were the only survivor     |")
                print("|   in a plane crash.              |")
                print("|   You were going to see your     |")
                print("|   Family for christmas.          |")
                print("|__________________________________|")
                print()
                print("YOU WIN!")
            else:
                print("YOU DIED OF HUNGER")
        else:
            print("YOU DIED OF HYPOHERMIA")
else:
    print("___________________________________")
    print("| * You Wander in the forest       |")
    print("|   You are now hungry.            |")
    print("|   You see a cabin.               |")
    print("|   enter it?                      |")
    print("|__________________________________|")
    print()
    des3 = input("(Y/N): ")
    if des3 == "Y":
        print("___________________________________")
        print("| * You find bags of cash.         |")
        print("|   probably a criminal hideout.   |")
        print("|   a man approaches you.          |")
        print("|   he kills you.                  |")
        print("|__________________________________|")
    else:
        print("___________________________________")
        print("| * You were seen by a robber      |")
        print("|   returning to his hideout       |")
        print("|   cabin.                         |")
        print("|__________________________________|")
        print()
        print("___________________________________")
        print("| * He approaches you              |")
        print("|   do you fight him or run?       |")
        print("|__________________________________|")
        print()
        des6 = input("(F/R): ")
        if des6 == "F":
            print()
            print("___________________________________")
            print("| * You throw a stone              |")
            print("|   he is knocked out.             |")
            print("|__________________________________|")
            print()
            print("___________________________________")
            print("| * You see a road leading to a    |")
            print("|   small village.                 |")
            print("|__________________________________|")
            print("___________________________________")
            print("| * The villagers feed you food.   |")
            print("|   They call a rescue helicopter. |")
            print("|   you reunite with your family.  |")
            print("|__________________________________|")
            print()
            print("___________________________________")
            print("| * You learn you had amnesia.     |")
            print("|   You were the only survivor     |")
            print("|   in a plane crash.              |")
            print("|   You were going to see your     |")
            print("|   Family for christmas.          |")
            print("|__________________________________|")
            print()
            print("YOU WIN!")
        else:
            print()
            print("You trip and fall off a cliff into a river")
            print("You Died")
